"""empty message

Revision ID: 2aa2d7a6838c
Revises: 2e856bdc8a9
Create Date: 2015-12-19 18:47:02.469690

"""

# revision identifiers, used by Alembic.
revision = '2aa2d7a6838c'
down_revision = '2e856bdc8a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme', sa.Column('outcome', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programme', 'outcome')
    ### end Alembic commands ###
