"""empty message

Revision ID: 40e2b5455058
Revises: 3f446d057054
Create Date: 2015-12-21 11:58:13.519231

"""

# revision identifiers, used by Alembic.
revision = '40e2b5455058'
down_revision = '3f446d057054'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inter_programme')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inter_programme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('live', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], [u'users.id'], name=u'inter_programme_user_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'inter_programme_pkey'),
    sa.UniqueConstraint('course_code', name=u'inter_programme_course_code_key'),
    sa.UniqueConstraint('slug', name=u'inter_programme_slug_key')
    )
    ### end Alembic commands ###
